// SmartConnect-facing system: AXI4 data slave + AXI-Lite CDMA control master.
// Host descriptors enter through the ready/valid task port.
module rigel_axi_scheduled_top #(parameter int WORDS_PER_BANK=512, WRITE_DEPTH=8, QUEUE_DEPTH=4,
    parameter logic [31:0] APERTURE_BASE=32'h80000000, CDMA_BASE=32'h00000000)(
    input logic clk, rst_n,
    input logic task_valid, output logic task_ready,
    input logic [7:0] task_id, task_dependency,
    input logic task_has_dependency, task_has_copy, task_copy_only,
    input logic [3:0] task_tile,
    input logic [31:0] task_pc, task_src, task_dst, task_bytes,
    output logic submit_error,
    output logic completion_valid, input logic completion_ready,
    output logic [7:0] completion_id,
    output logic [3:0] completion_tile,
    output logic completion_error,
    output logic [255:0] completed, failed,
    output logic [15:0] busy, done, fault,
    input logic [3:0] host_tile,
    input logic [31:0] s_axi_awaddr,s_axi_araddr,
    input logic [7:0] s_axi_awlen,s_axi_arlen,
    input logic [2:0] s_axi_awsize,s_axi_arsize,
    input logic [1:0] s_axi_awburst,s_axi_arburst,
    input logic [3:0] s_axi_awid,s_axi_arid,
    input logic s_axi_awvalid,s_axi_wvalid,s_axi_bready,s_axi_arvalid,s_axi_rready,
    output logic s_axi_awready,s_axi_wready,s_axi_bvalid,s_axi_arready,s_axi_rvalid,
    input logic [127:0] s_axi_wdata,
    input logic [15:0] s_axi_wstrb,
    input logic s_axi_wlast,
    output logic [3:0] s_axi_bid,s_axi_rid,
    output logic [1:0] s_axi_bresp,s_axi_rresp,
    output logic [127:0] s_axi_rdata,
    output logic s_axi_rlast,
    output logic [31:0] m_axi_awaddr,m_axi_wdata,m_axi_araddr,
    output logic [2:0] m_axi_awprot,m_axi_arprot,
    output logic [3:0] m_axi_wstrb,
    output logic m_axi_awvalid,m_axi_wvalid,m_axi_bready,m_axi_arvalid,m_axi_rready,
    input logic m_axi_awready,m_axi_wready,m_axi_bvalid,m_axi_arready,m_axi_rvalid,
    input logic [1:0] m_axi_bresp,m_axi_rresp,
    input logic [31:0] m_axi_rdata
);
    rv_if #(.DATA_WIDTH(128)) host_read_req(),host_write_req(),host_read_rsp(),host_write_rsp();
    logic copy_valid,copy_ready,copy_done,copy_error,copy_active;
    logic [3:0] copy_tile,active_tile;
    logic [31:0] copy_src,copy_dst,copy_bytes;
    always_ff @(posedge clk) begin
        if(!rst_n) begin copy_active<=0; active_tile<=0; end
        else begin
            if(copy_valid && copy_ready) begin copy_active<=1; active_tile<=copy_tile; end
            if(copy_done) copy_active<=0;
        end
    end
    mesh_axi_gateway #(.APERTURE_BASE(APERTURE_BASE)) gateway(
        .clk(clk),.rst_n(rst_n),.destination_tile(copy_active?active_tile:host_tile),
        .host_read_req(host_read_req),.host_write_req(host_write_req),
        .host_read_rsp(host_read_rsp),.host_write_rsp(host_write_rsp),
        .s_axi_awaddr(s_axi_awaddr),
        .s_axi_araddr(s_axi_araddr),
        .s_axi_awlen(s_axi_awlen),
        .s_axi_arlen(s_axi_arlen),
        .s_axi_awsize(s_axi_awsize),
        .s_axi_arsize(s_axi_arsize),
        .s_axi_awburst(s_axi_awburst),
        .s_axi_arburst(s_axi_arburst),
        .s_axi_awid(s_axi_awid),
        .s_axi_arid(s_axi_arid),
        .s_axi_awvalid(s_axi_awvalid),
        .s_axi_wvalid(s_axi_wvalid),
        .s_axi_bready(s_axi_bready),
        .s_axi_arvalid(s_axi_arvalid),
        .s_axi_rready(s_axi_rready),
        .s_axi_awready(s_axi_awready),
        .s_axi_wready(s_axi_wready),
        .s_axi_bvalid(s_axi_bvalid),
        .s_axi_arready(s_axi_arready),
        .s_axi_rvalid(s_axi_rvalid),
        .s_axi_wdata(s_axi_wdata),
        .s_axi_wstrb(s_axi_wstrb),
        .s_axi_wlast(s_axi_wlast),
        .s_axi_bid(s_axi_bid),
        .s_axi_rid(s_axi_rid),
        .s_axi_bresp(s_axi_bresp),
        .s_axi_rresp(s_axi_rresp),
        .s_axi_rdata(s_axi_rdata),
        .s_axi_rlast(s_axi_rlast));
    mesh_cdma_controller #(.BASE_ADDR(CDMA_BASE)) transfer_controller(
        .clk(clk),.rst_n(rst_n),.copy_valid(copy_valid),.copy_ready(copy_ready),
        .copy_src(copy_src),.copy_dst(copy_dst),.copy_bytes(copy_bytes),.copy_done(copy_done),.copy_error(copy_error),
        .m_axi_awaddr(m_axi_awaddr),
        .m_axi_wdata(m_axi_wdata),
        .m_axi_araddr(m_axi_araddr),
        .m_axi_awprot(m_axi_awprot),
        .m_axi_arprot(m_axi_arprot),
        .m_axi_wstrb(m_axi_wstrb),
        .m_axi_awvalid(m_axi_awvalid),
        .m_axi_wvalid(m_axi_wvalid),
        .m_axi_bready(m_axi_bready),
        .m_axi_arvalid(m_axi_arvalid),
        .m_axi_rready(m_axi_rready),
        .m_axi_awready(m_axi_awready),
        .m_axi_wready(m_axi_wready),
        .m_axi_bvalid(m_axi_bvalid),
        .m_axi_arready(m_axi_arready),
        .m_axi_rvalid(m_axi_rvalid),
        .m_axi_bresp(m_axi_bresp),
        .m_axi_rresp(m_axi_rresp),
        .m_axi_rdata(m_axi_rdata));
    rigel_scheduled_mesh_system #(.WORDS_PER_BANK(WORDS_PER_BANK),.WRITE_DEPTH(WRITE_DEPTH),.QUEUE_DEPTH(QUEUE_DEPTH)) system_core(
        .clk(clk),.rst_n(rst_n),.host_read_req(host_read_req),.host_write_req(host_write_req),
        .host_read_rsp(host_read_rsp),.host_write_rsp(host_write_rsp),
        .copy_valid(copy_valid),.copy_ready(copy_ready),.copy_tile(copy_tile),
        .copy_src(copy_src),.copy_dst(copy_dst),.copy_bytes(copy_bytes),.copy_done(copy_done),.copy_error(copy_error),
        .task_valid(task_valid),
        .task_ready(task_ready),
        .task_id(task_id),
        .task_dependency(task_dependency),
        .task_has_dependency(task_has_dependency),
        .task_has_copy(task_has_copy),.task_copy_only(task_copy_only),
        .task_tile(task_tile),
        .task_pc(task_pc),
        .task_src(task_src),
        .task_dst(task_dst),
        .task_bytes(task_bytes),.submit_error(submit_error),
        .completion_valid(completion_valid),
        .completion_ready(completion_ready),
        .completion_id(completion_id),
        .completion_tile(completion_tile),
        .completion_error(completion_error),.completed(completed),.failed(failed),.busy(busy),.done(done),.fault(fault));
endmodule
